# =====  Controller params  ======

# DMP parameters
N_kernels: 30
a_z: 16
b_z: 4
train_method: "LWR"
a_filt: 1.0 # filtering parameter for the numerical differentiation

P0_g_hat: [1.0; 1.0; 1.0]
P0_tau_hat: [1.0]
R_v: [0.001; 0.001; 0.001]
Q_W: [0.1; 0.1; 0.1; 0.1]
a_p: 0.0

# DMP goal and time scaling
g_scale: [-1.0; 1.3; 1.5]
tau_scale: 1.5

# starting conditions for controller run
f_thres: -1.0 # norm(force)

# target impedance params
M: [1.0; 1.0; 1.0]
D: [30.0; 30.0; 30.0]
K_d: [250; 250; 250.0]
# D_d: [40; 40; 40.0] #2*sqrt(M.*K)
k_click: 0.5
ff_gains: [1.0; 1.0; 1.0] # feedforward gains for the target impedance model
a_force: 0.05 # iir 1st order filter coeff for filtering force measurements

# leader-follower sigmoid function params  1 / ( 1 + exp(a_m*(norm(F)-c_m)) )
a_m: 3.0
c_m: 4.0
