# =====  Controller params  ======

# DMP parameters
N_kernels: 20
a_z: 20
b_z: 5
train_method: "LWR"
a_filt: 1.0 # filtering parameter for the numerical differentiation

P0_g_hat: [1.0; 1.0; 1.0]
P0_tau_hat: [1.0]
R_v: [1000; 1000; 1000]
Q_W: [0.005; 0.005; 0.005; 0.005]
a_p: 1.002
enable_constraints: true
g_up_bound: [0.65; 0.75; 0.7]
g_low_bound: [-0.65; 0.05; 0.15]
tau_up_bound: 60.0
tau_low_bound: 1.5

dmp_mod: 2

# DMP goal and time scaling
g_scale: [1.0; 1.0; 1.0]
tau_scale: 1.0

# starting conditions for controller run
f_thres: -1.0 # norm(force)

# target impedance params
M: [4.0; 4.0; 4.0]
D: [15.0; 15.0; 15.0]

M_d: [10.0; 10.0; 10.0]

k_click: 0.5
a_force: 0.5 # iir 1st order filter coeff for filtering force measurements
